const resultCode = {

    CODE_SUCCESS: 'SUCCESS',
    CODE_ERROR: 'ERR_SYSTEM',
    CODE_ERROR_SQL: 'ERR_SQL_QUERY',
    CODE_ERROR_VALIDATE: 'ERR_VALIDATE',
    CODE_ERROR_AUTHENTICATION: 'ERR_AUTHENTICATION',
    CODE_ERROR_NOTFOUND: 'ERR_DATA_NOTFOUND',
    CODE_ERROR_TOKEN: 'ERR_TOKEN',
    CODE_ERROR_DUP: 'ERR_DUPLICATE_DATA',
    CODE_ERROR_LOGIN: 'LOGIN FAILED',
    CODE_ERROR_SERVICE: 'ERR_SERVICE',
    CODE_ERROR_VALIDATE_CUSTOM: 'ERR_VALIDATE_CUSTOM',
    CODE_ERROR_NOTEXIST: 'ERR_DATA_NOTEXIST',
    CODE_ERROR_PASSWORD: 'ERR_PASSWORD_WRONG'

};

export default resultCode;