// define type action of menu
const menuActionType = {
  //Menu request
  MENU_REQUEST: "MENU_REQUEST",

  // create
  MENU_CREATE_SUCCESS: "MENU_CREATE_SUCCESS",
  MENU_CREATE_FAILURE: "MENU_CREATE_FAILURE",

  // eidit
  MENU_EDIT_SUCCESS: "MENU_EDIT_SUCCESS",
  MENU_EDIT_FAILURE: "MENU_EDIT_FAILURE",

  // clone
  MENU_CLONE_SUCCESS: "MENU_CLONE_SUCCESS",
  MENU_CLONE_FAILURE: "MENU_CLONE_FAILURE",

  //list menu
  MENU_LIST_SUCCESS: "MENU_LIST_SUCCESS",
  MENU_LIST_FAILURE: "MENU_LIST_FAILURE",

  //list product by Menu Id
  MENU_LISTPRODUCT_SUCCESS: "MENU_LISTPRODUCT_SUCCESS",
  MENU_LISTPRODUCT_FAILURE: "MENU_LISTPRODUCT_FAILURE",

  // get menu detail by menu id
  MENU_GET_DETAIL_SUCCESS: "MENU_GET_DETAIL_SUCCESS",
  MENU_GET_DETAIL_FAILURE: "MENU_GET_DETAIL_FAILURE",

  // get summary
  MENU_GET_SUMMARY_SUCCESS: "MENU_GET_SUMMARY_SUCCESS",
  MENU_GET_SUMMARY_FAILURE: "MENU_GET_SUMMARY_FAILURE"
};

export default menuActionType;
