// define type action of user
const userActionType = {
    // register
    USERS_REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    USERS_REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    USERS_REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    // login
    USERS_LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    USERS_LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    USERS_LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    // logout
    USERS_LOGOUT_REQUEST: 'USERS_LOGOUT_REQUEST',
    USERS_LOGOUT_SUCCESS: 'USERS_LOGOUT_SUCCESS',
    USERS_LOGOUT_FAILURE: 'USERS_LOGOUT_FAILURE',

    // reload page
    USERS_RELOAD_REQUEST: 'USERS_RELOAD_REQUEST',

    // change avatar
    USERS_CHANGE_AVATAR_SUCCESS: 'USERS_CHANGE_AVATAR_SUCCESS',
    USERS_CHANGE_AVATAR_FAILURE: 'USERS_CHANGE_AVATAR_FAILURE',

    // change password
    USERS_CHANGE_PASSWORD_SUCCESS: 'USERS_CHANGE_PASSWORD_SUCCESS',
    USERS_CHANGE_PASSWORD_FAILURE: 'USERS_CHANGE_PASSWORD_FAILURE'
};

export default userActionType;